# Generated by Django 5.0.6 on 2024-06-13 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtor', models.TextField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_due', models.DateField()),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('creditor',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts',
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
